### ISSUE TITLE
lib.rs isn't compiled unless `features = ["no_std"]` is passed

### ISSUE THREAD

**Issue by pwoolcoc** [derekjw/try_from#9]
I think this line: https://github.com/derekjw/try_from/blob/master/src/lib.rs#L1 is making it so that unless `feature = ["no_std"]` is specified, the entire crate is empty. The empty docs.rs page seems to confirm this: https://docs.rs/try_from .

You probably want to do `#![cfg_attr(feature = "no_std", no_std)]` instead.

**Comment by derekjw** [comment]
Thanks, I'll give that a try. @gbip and myself have been trying to figure out what's wrong

**Comment by derekjw** [comment]
Looks like that fix it, I've published a new version. I'll let @gbip look at making sure no_std support is still working, as I'm completely unfamiliar with it. Thanks again!

**Comment by gbip** [comment]
Thank you for figuring this out :smile:
